# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiobase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.CharField(max_length=12)),
                ('empresaduena', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('coordenadas', models.CharField(max_length=250)),
            ],
        ),
    ]
