# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('radiobase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiobase',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='radiobase',
            name='latitud',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiobase',
            name='longitud',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
